portfolio/authapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profileinfo/', views.profileinfo, name='profileinfo'),
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from error_pages.views import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='home/', permanent=True)),
    path('home/', include('webportfolioapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('accounts/', include('authapp.urls')),
    path('expenses/', include('expensesapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'error_pages.views.error_404'

portfolio/webportfolioapp/urls.py
from django.urls import path
from webportfolioapp import views

urlpatterns = [
    path('', views.home, name='home'),
    path('softskills/', views.softskills, name='softskills'),
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.success_message, name='success_message'),
]

portfolio/webportfolioapp/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

portfolio/webportfolioapp/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }

portfolio/webportfolioapp/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm


def home(request):
    return render(request, 'webportfolioapp/home.html')

def softskills(request):
    return render(request, 'webportfolioapp/softskills.html')

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_message')
    else:
        form = ContactForm()
    return render(request, 'webportfolioapp/contact.html', {'form': form})

def success_message(request):
    return render(request, 'webportfolioapp/success.html')

portfolio/webportfolioapp/templates/webportfolioapp/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact{% endblock %}

{% block content %}
<div id="form" class="container mt-5">
    <h1>Contact Form</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Email address</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="id_message" class="form-label">Message</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>
{% endblock %}

{% block style %}
<style>
    #form {
        width: 40%;
    }

    @media (max-width: 768px) {
        #form {
            width: 90%;
        }
    }
</style>
{% endblock %}

portfolio/webportfolioapp/templates/webportfolioapp/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container text-center mt-5">
        <div class="row align-items-center">
            <div class="col-md-6 order-md-1">
                <h1 style="color: #b2bed7; font-size: 72px;">Hello, World!</h1>
                <h2 style="color: #b2bed7; font-size: 48px;">My name is</h2>
                <h3 style="color: #ff0; font-size: 32px;">Bastian Landskron</h3>
            </div>
            <div class="col-md-6 order-md-2">
                <img src="{% static 'img/perfil.jpg' %}"  alt="Perfil" style="width:60%; border-radius:50%; box-shadow: 0px 0px 20px rgba(106, 21, 162, 0.5);">
            </div>
        </div>
        <img align="center" src="https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&color=F7F400&center=true&vCenter=true&random=false&width=435&lines=Full+Stack+Developer+Django" alt="Typing SVG" />
    </div>
{% endblock %}

portfolio/webportfolioapp/templates/webportfolioapp/softskills.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container text-center mb-5" id="wordcloud-container" style="width: 90%; height: 100px;"></div>
{% endblock %}
    

portfolio/webportfolioapp/templates/webportfolioapp/success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Success{% endblock %}

{% block content %}
    <div class="container text-center mt-5">
        <h1>¡Mensaje enviado con éxito!</h1>
        <p>Gracias por contactarnos. Nos pondremos en contacto contigo pronto.</p>
    </div>
{% endblock %}
    